# Generated by Django 5.1.4 on 2024-12-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=0),
        ),
    ]
