# Generated by Django 5.1.4 on 2024-12-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
