# Generated by Django 5.1.4 on 2024-12-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
