POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###

### Obter token JWT para autenticação
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

HTTP/1.1 200
[Asserts]
jsonpath "$.access" exists

[Captures]
token = jsonpath "$.access"

###

### Obter lista de filmes sem autenticação (esperado: 401 Unauthorized)
GET http://127.0.0.1:8000/movies/
Content-Type: application/json

###

### Obter lista de filmes com autenticação
GET http://127.0.0.1:8000/movies/
Authorization: Bearer {{token}}
Content-Type: application/json
